image: node:latest # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - CI=true npm test

test_variables:
  script:
    - echo $REACT_APP_MOVIE_API_KEY

pages:
  stage: deploy
  script:
    - CI=false REACT_APP_MOVIE_API_KEY=$REACT_APP_MOVIE_API_KEY npm run build
    - rm -rf public
    - mv build public
  tags:
    - shared
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch
